# Travis CI script
language: c

# Dependencies
before_install:

# Those handled by apt-get
- sudo apt-get install make gcc pkg-config libjansson4 libsqlite3-dev libglib2.0-dev

# libsodium
- git clone git://github.com/jedisct1/libsodium.git
- ( cd libsodium; ./autogen.sh; ./configure; make check; sudo make install; sudo ldconfig )

# libzmq
- git clone git://github.com/zeromq/libzmq.git
- ( cd libzmq; ./autogen.sh; ./configure; make; sudo make install )

# czmq bindings
- git clone git://github.com/zeromq/czmq.git
- ( cd czmq; ./autogen.sh; ./configure; make; sudo make install )

# Building sauvegarde
script:

- ./autoclean.sh && ./autogen.sh && ./configure --prefix=/home/dup/local --enable-debug --disable-silent && make && sudo make install


