# Travis CI script
language: c
sudo: false

# Compilers to test.
compiler:
    - gcc
    - clang

# Dependencies
addons:
  apt:
    packages:
    - build-essential
    - intltool
    - gettext
    - pkg-config
    - libsqlite3-dev
    - libglib2.0-dev
    - libcurl4-openssl-dev

install:
    # jansson (not found by travis's apt as of 24.08.2015)
    - git clone git://github.com/akheron/jansson.git
    - (cd jansson;  autoreconf -f -i ; CFLAGS=-Werror ./configure --prefix=$HOME/local; make; make install)

    # libmicrohttpd (the one in ubuntu 12.04 is too old).
    - wget --quiet -c http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.44.tar.gz
    - (tar zxf libmicrohttpd-0.9.44.tar.gz; cd libmicrohttpd-0.9.44; ./configure --prefix=$HOME/local; make; make install)

# Building sauvegarde
script:
    - export PATH=$PATH:$HOME/local/bin
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/local/lib/pkgconfig
    - ./autoclean.sh && ./autogen.sh && ./configure --prefix=$HOME/local --enable-debug --disable-silent && make && make install && $HOME/local/bin/cdpfglclient --version && $HOME/local/bin/cdpfglserver --version && $HOME/local/bin/cdpfglrestore --version
    - $HOME/build/dupgit/sauvegarde/tests/launch_tests.bash

# irc bot notification
notifications:
  irc:
    - "irc.oftc.net#sauvegarde"
