# Travis CI script
language: c

# Compilers to test.
compiler:
    - gcc
    - clang

# Dependencies
before_install:
    # update packages definitions
    - sudo apt-get update -qq

install:
    # Those handled by apt-get
    - sudo apt-get install -qq build-essential intltool gettext pkg-config libsqlite3-dev libglib2.0-dev libcurl4-openssl-dev libmicrohttpd-dev

    # jansson
    - git clone git://github.com/akheron/jansson.git
    - (cd jansson;  autoreconf -f -i ; CFLAGS=-Werror ./configure; make; sudo make install; sudo ldconfig)

    # libcurl
    #- git clone https://github.com/bagder/curl.git
    #- (cd curl; ./buildconf; ./configure; make; sudo make install; sudo ldconfig)

    # libmicrohttpd
    #- wget --quiet -c http://mirror.ibcp.fr/pub/gnu/libmicrohttpd/libmicrohttpd-0.9.39.tar.gz
    #- (tar zxf libmicrohttpd-0.9.39.tar.gz; cd libmicrohttpd-0.9.39; ./configure; make; sudo make install; sudo ldconfig )

# Building sauvegarde
script:

    - ./autoclean.sh && ./autogen.sh && ./configure --prefix=/home/dup/local --enable-debug --disable-silent && make && sudo make install && /home/dup/local/bin/client --version && /home/dup/local/bin/serveur --version && /home/dup/local/bin/restaure --version


