# Travis CI script
language: c
sudo: false

# Compilers to test.
compiler:
    - gcc
    - clang

# Dependencies
addons:
  apt:
    packages:
    - build-essential
    - intltool
    - gettext
    - pkg-config
    - libsqlite3-dev
    - libglib2.0-dev
    - libcurl4-openssl-dev

install:
    # jansson
    - git clone git://github.com/akheron/jansson.git
    - (cd jansson;  autoreconf -f -i ; CFLAGS=-Werror ./configure --prefix=$PWD/local; make; make install)

    # libmicrohttpd
    - wget --quiet -c http://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-0.9.42.tar.gz
    - (tar zxf libmicrohttpd-0.9.42.tar.gz; cd libmicrohttpd-0.9.42; ./configure --prefix=$PWD/local; make; make install)

# Building sauvegarde
script:

    - export PATH=$PATH:$PWD/local/bin
    - export PKG_CONFIG=$PKG_CONFIG:$PWD/local/lib/pkgconfig/
    - ./autoclean.sh && ./autogen.sh && ./configure --prefix=$PWD/local --enable-debug --disable-silent && make && make install && $PWD/local/bin/client --version && $PWD/local/bin/serveur --version && $PWD/local/bin/restaure --version

# irc bot notification
notifications:
  irc:
    - "irc.oftc.net#sauvegarde"
